DEVICE=iphoneos
SIMULATOR=iphonesimulator

TARGET=YTLibrary
Folder=${TARGET}

FILE_NAME=libYT.a

#xcodebuild -sdk $DEVICE "ARCHS=armv6 armv7" clean build -target $TARGET
#xcodebuild -sdk $SIMULATOR "ARCHS=i386 x86_64" "VALID_ARCHS=i386 x86_64" clean build -target $TARGET
xcodebuild -sdk $DEVICE "ARCHS=armv6 armv7" -target $TARGET
xcodebuild -sdk $SIMULATOR "ARCHS=i386 x86_64" "VALID_ARCHS=i386 x86_64" -target $TARGET

#echo "COPY_PHASE_STRIP=$COPY_PHASE_STRIP"
echo "JAVA_ZIP_FLAGS=$JAVA_ZIP_FLAGS"
echo "SDK_PRODUCT_BUILD_VERSION=$SDK_PRODUCT_BUILD_VERSION"
echo "HEADERMAP_INCLUDES_PROJECT_HEADERS=$HEADERMAP_INCLUDES_PROJECT_HEADERS"
echo "EXECUTABLES_FOLDER_PATH=$EXECUTABLES_FOLDER_PATH"
echo "LOCAL_APPS_DIR=$LOCAL_APPS_DIR"
echo "REMOVE_CVS_FROM_RESOURCES=$REMOVE_CVS_FROM_RESOURCES"
echo "SED=$SED"
echo "SYSTEM_DEVELOPER_UTILITIES_DIR=$SYSTEM_DEVELOPER_UTILITIES_DIR"
echo "PRESERVE_DEAD_CODE_INITS_AND_TERMS=$PRESERVE_DEAD_CODE_INITS_AND_TERMS"
echo "UNLOCALIZED_RESOURCES_FOLDER_PATH=$UNLOCALIZED_RESOURCES_FOLDER_PATH"
echo "SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR=$SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR"
echo "PRODUCT_NAME=$PRODUCT_NAME"
echo "TEMP_FILES_DIR=$TEMP_FILES_DIR"
echo "LIBRARY_FLAG_NOSPACE=$LIBRARY_FLAG_NOSPACE"
echo "USE_DYNAMIC_NO_PIC=$USE_DYNAMIC_NO_PIC"
echo "DEVELOPER_DIR=$DEVELOPER_DIR"
echo "LD_GENERATE_MAP_FILE=$LD_GENERATE_MAP_FILE"
echo "DEVELOPER_SDK_DIR=$DEVELOPER_SDK_DIR"
echo "LC_MONETARY=$LC_MONETARY"
echo "REZ_COLLECTOR_DIR=$REZ_COLLECTOR_DIR"
echo "TERM_PROGRAM=$TERM_PROGRAM"
echo "MAC_OS_X_PRODUCT_BUILD_VERSION=$MAC_OS_X_PRODUCT_BUILD_VERSION"
echo "GCC_WARN_UNUSED_FUNCTION=$GCC_WARN_UNUSED_FUNCTION"
echo "GCC_SYMBOLS_PRIVATE_EXTERN=$GCC_SYMBOLS_PRIVATE_EXTERN"
echo "APPLE_INTERNAL_TOOLS=$APPLE_INTERNAL_TOOLS"
echo "GCC_C_LANGUAGE_STANDARD=$GCC_C_LANGUAGE_STANDARD"
echo "DEVELOPER_FRAMEWORKS_DIR_QUOTED=$DEVELOPER_FRAMEWORKS_DIR_QUOTED"
echo "PRIVATE_HEADERS_FOLDER_PATH=$PRIVATE_HEADERS_FOLDER_PATH"
echo "NATIVE_ARCH_64_BIT=$NATIVE_ARCH_64_BIT"
echo "LIBRARY_FLAG_PREFIX=$LIBRARY_FLAG_PREFIX"
echo "CONFIGURATION=$CONFIGURATION"
echo "SHELL=$SHELL"
echo "GCC_WARN_ABOUT_RETURN_TYPE=$GCC_WARN_ABOUT_RETURN_TYPE"
echo "TERM=$TERM"
echo "COPY_RESOURCES_FROM_STATIC_FRAMEWORKS=$COPY_RESOURCES_FROM_STATIC_FRAMEWORKS"
echo "PROJECT=$PROJECT"
echo "VERSION_INFO_BUILDER=$VERSION_INFO_BUILDER"
echo "OBJROOT=$OBJROOT"
echo "PLUGINS_FOLDER_PATH=$PLUGINS_FOLDER_PATH"
echo "DEVELOPMENT_LANGUAGE=$DEVELOPMENT_LANGUAGE"
echo "PRODUCT_TYPE=$PRODUCT_TYPE"
echo "SYSTEM_DEVELOPER_TOOLS=$SYSTEM_DEVELOPER_TOOLS"
echo "SYSTEM_DOCUMENTATION_DIR=$SYSTEM_DOCUMENTATION_DIR"
echo "SYSTEM_DEVELOPER_DIR=$SYSTEM_DEVELOPER_DIR"
echo "MACH_O_TYPE=$MACH_O_TYPE"
echo "TMPDIR=$TMPDIR"
echo "PLATFORM_DEVELOPER_USR_DIR=$PLATFORM_DEVELOPER_USR_DIR"
echo "CLASS_FILE_DIR=$CLASS_FILE_DIR"
echo "Apple_PubSub_Socket_Render=$Apple_PubSub_Socket_Render"
echo "INSTALL_DIR=$INSTALL_DIR"
echo "TARGET_BUILD_DIR=$TARGET_BUILD_DIR"
echo "SYMBOL_REPOSITORY_DIR=$SYMBOL_REPOSITORY_DIR"
echo "PBDEVELOPMENTPLIST_PATH=$PBDEVELOPMENTPLIST_PATH"
echo "WRAPPER_EXTENSION=$WRAPPER_EXTENSION"
echo "CLEAN_PRECOMPS=$CLEAN_PRECOMPS"
echo "SYSTEM_DEVELOPER_DOC_DIR=$SYSTEM_DEVELOPER_DOC_DIR"
echo "JAVA_APP_STUB=$JAVA_APP_STUB"
echo "LC_NUMERIC=$LC_NUMERIC"
echo "PLIST_FILE_OUTPUT_FORMAT=$PLIST_FILE_OUTPUT_FORMAT"
echo "CONFIGURATION_TEMP_DIR=$CONFIGURATION_TEMP_DIR"
echo "TARGETED_DEVICE_FAMILY=$TARGETED_DEVICE_FAMILY"
echo "APPLE_INTERNAL_DIR=$APPLE_INTERNAL_DIR"
echo "AVAILABLE_PLATFORMS=$AVAILABLE_PLATFORMS"
echo "GCC_WARN_UNDECLARED_SELECTOR=$GCC_WARN_UNDECLARED_SELECTOR"
echo "PFE_FILE_C_DIALECTS=$PFE_FILE_C_DIALECTS"
echo "MAC_OS_X_VERSION_MINOR=$MAC_OS_X_VERSION_MINOR"
echo "SDKROOT=$SDKROOT"
echo "NATIVE_ARCH_32_BIT=$NATIVE_ARCH_32_BIT"
echo "SHARED_SUPPORT_FOLDER_PATH=$SHARED_SUPPORT_FOLDER_PATH"
echo "LIBRARY_SEARCH_PATHS=$LIBRARY_SEARCH_PATHS"
echo "BUILD_VARIANTS=$BUILD_VARIANTS"
echo "PLATFORM_NAME=$PLATFORM_NAME"
echo "INFOPLIST_PREPROCESS=$INFOPLIST_PREPROCESS"
echo "SYSTEM_DEVELOPER_RELEASENOTES_DIR=$SYSTEM_DEVELOPER_RELEASENOTES_DIR"
echo "USER_LIBRARY_DIR=$USER_LIBRARY_DIR"
echo "DSTROOT=$DSTROOT"
echo "SDK_NAME=$SDK_NAME"
echo "TEMP_DIR=$TEMP_DIR"
echo "OS=$OS"
echo "GCC_INLINES_ARE_PRIVATE_EXTERN=$GCC_INLINES_ARE_PRIVATE_EXTERN"
echo "LD_MAP_FILE_PATH=$LD_MAP_FILE_PATH"
echo "LOCALIZED_RESOURCES_FOLDER_PATH=$LOCALIZED_RESOURCES_FOLDER_PATH"
echo "CONFIGURATION_BUILD_DIR=$CONFIGURATION_BUILD_DIR"
echo "WRAPPER_SUFFIX=$WRAPPER_SUFFIX"
echo "APPLE_INTERNAL_DEVELOPER_DIR=$APPLE_INTERNAL_DEVELOPER_DIR"
echo "XCODE_PRODUCT_BUILD_VERSION=$XCODE_PRODUCT_BUILD_VERSION"
echo "EFFECTIVE_PLATFORM_NAME=$EFFECTIVE_PLATFORM_NAME"
echo "DERIVED_FILES_DIR=$DERIVED_FILES_DIR"
echo "OBJECT_FILE_DIR_normal=$OBJECT_FILE_DIR_normal"
echo "DEVELOPER_APPLICATIONS_DIR=$DEVELOPER_APPLICATIONS_DIR"
echo "PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES=$PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES"
echo "GCC_PFE_FILE_C_DIALECTS=$GCC_PFE_FILE_C_DIALECTS"
echo "DOCUMENTATION_FOLDER_PATH=$DOCUMENTATION_FOLDER_PATH"
echo "GROUP=$GROUP"
echo "VERSION_INFO_STRING=$VERSION_INFO_STRING"
echo "USER=$USER"
echo "SVN_EDITOR=$SVN_EDITOR"
echo "TEST_AFTER_BUILD=$TEST_AFTER_BUILD"
echo "CURRENT_ARCH=$CURRENT_ARCH"
echo "JAVA_JAR_FLAGS=$JAVA_JAR_FLAGS"
echo "EXECUTABLE_PATH=$EXECUTABLE_PATH"
echo "OSAC=$OSAC"
echo "OTHER_LDFLAGS=$OTHER_LDFLAGS"
echo "COMMAND_MODE=$COMMAND_MODE"
echo "DEPLOYMENT_POSTPROCESSING=$DEPLOYMENT_POSTPROCESSING"
echo "TARGET_NAME=$TARGET_NAME"
echo "PLATFORM_VERSION_AVAILABILITY_H_FORMAT=$PLATFORM_VERSION_AVAILABILITY_H_FORMAT"
echo "EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES=$EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES"
echo "GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS=$GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS"
echo "CLONE_HEADERS=$CLONE_HEADERS"
echo "YACC=$YACC"
echo "STRIP_STYLE=$STRIP_STYLE"
echo "DEVELOPER_USR_DIR=$DEVELOPER_USR_DIR"
echo "GCC3_VERSION=$GCC3_VERSION"
echo "VALIDATE_PRODUCT=$VALIDATE_PRODUCT"
echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK"
echo "OBJECT_FILE_DIR=$OBJECT_FILE_DIR"
echo "PLATFORM_PREFERRED_ARCH=$PLATFORM_PREFERRED_ARCH"
echo "DOXYGEN_PATH=$DOXYGEN_PATH"
echo "VERSIONPLIST_PATH=$VERSIONPLIST_PATH"
echo "TARGETNAME=$TARGETNAME"
echo "SYSTEM_APPS_DIR=$SYSTEM_APPS_DIR"
echo "__CF_USER_TEXT_ENCODING=$__CF_USER_TEXT_ENCODING"
echo "BUILT_PRODUCTS_DIR=$BUILT_PRODUCTS_DIR"
echo "ICONV=$ICONV"
echo "PACKAGE_TYPE=$PACKAGE_TYPE"
echo "XCODE_APP_SUPPORT_DIR=$XCODE_APP_SUPPORT_DIR"
echo "ENABLE_OPENMP_SUPPORT=$ENABLE_OPENMP_SUPPORT"
echo "XCODE_VERSION_ACTUAL=$XCODE_VERSION_ACTUAL"
echo "HEADER_SEARCH_PATHS=$HEADER_SEARCH_PATHS"
echo "DERIVED_FILE_DIR=$DERIVED_FILE_DIR"
echo "LOCAL_ADMIN_APPS_DIR=$LOCAL_ADMIN_APPS_DIR"
echo "USER_APPS_DIR=$USER_APPS_DIR"
echo "DO_HEADER_SCANNING_IN_JAM=$DO_HEADER_SCANNING_IN_JAM"
echo "SCRIPT_OUTPUT_FILE_COUNT=$SCRIPT_OUTPUT_FILE_COUNT"
echo "GCC_VERSION=$GCC_VERSION"
echo "DERIVED_SOURCES_DIR=$DERIVED_SOURCES_DIR"
echo "GCC_OPTIMIZATION_LEVEL=$GCC_OPTIMIZATION_LEVEL"
echo "PKGINFO_PATH=$PKGINFO_PATH"
echo "DEAD_CODE_STRIPPING=$DEAD_CODE_STRIPPING"
echo "DWARF_DSYM_FOLDER_PATH=$DWARF_DSYM_FOLDER_PATH"
echo "ENABLE_HEADER_DEPENDENCIES=$ENABLE_HEADER_DEPENDENCIES"
echo "SET_FILE_MODE_OWNER_GROUP=$SET_FILE_MODE_OWNER_GROUP"
echo "SHARED_DERIVED_FILE_DIR=$SHARED_DERIVED_FILE_DIR"
echo "PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=$PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR"
echo "GCC_VERSION_IDENTIFIER=$GCC_VERSION_IDENTIFIER"
echo "SYSTEM_DEMOS_DIR=$SYSTEM_DEMOS_DIR"
echo "COPYING_PRESERVES_HFS_DATA=$COPYING_PRESERVES_HFS_DATA"
echo "REZ_SEARCH_PATHS=$REZ_SEARCH_PATHS"
echo "GCC_TREAT_WARNINGS_AS_ERRORS=$GCC_TREAT_WARNINGS_AS_ERRORS"
echo "BUILD_COMPONENTS=$BUILD_COMPONENTS"
echo "JAVA_USE_DEPENDENCIES=$JAVA_USE_DEPENDENCIES"
echo "ALTERNATE_MODE=$ALTERNATE_MODE"
echo "OPTIMIZATION_LEVEL=$OPTIMIZATION_LEVEL"
echo "INSTALL_GROUP=$INSTALL_GROUP"
echo "PATH=$PATH"
echo "GCC_OBJC_LEGACY_DISPATCH=$GCC_OBJC_LEGACY_DISPATCH"
echo "LC_MESSAGES=$LC_MESSAGES"
echo "ONLY_ACTIVE_ARCH=$ONLY_ACTIVE_ARCH"
echo "INFOPLIST_OUTPUT_FORMAT=$INFOPLIST_OUTPUT_FORMAT"
echo "INSTALL_MODE_FLAG=$INSTALL_MODE_FLAG"
echo "ACTION=$ACTION"
echo "STANDARD_C_PLUS_PLUS_LIBRARY_TYPE=$STANDARD_C_PLUS_PLUS_LIBRARY_TYPE"
echo "DEVELOPER_TOOLS_DIR=$DEVELOPER_TOOLS_DIR"
echo "SHARED_PRECOMPS_DIR=$SHARED_PRECOMPS_DIR"
echo "PROJECT_NAME=$PROJECT_NAME"
echo "STRINGS_FILE_OUTPUT_ENCODING=$STRINGS_FILE_OUTPUT_ENCODING"
echo "FULL_PRODUCT_NAME=$FULL_PRODUCT_NAME"
echo "HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=$HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES"
echo "SDK_DIR=$SDK_DIR"
echo "COMPRESS_PNG_FILES=$COMPRESS_PNG_FILES"
echo "LD_OPENMP_FLAGS=$LD_OPENMP_FLAGS"
echo "GID=$GID"
echo "LC_COLLATE=$LC_COLLATE"
echo "SEPARATE_STRIP=$SEPARATE_STRIP"
echo "INSTALL_OWNER=$INSTALL_OWNER"
echo "PLATFORM_DIR=$PLATFORM_DIR"
echo "CONTENTS_FOLDER_PATH=$CONTENTS_FOLDER_PATH"
echo "PWD=$PWD"
echo "STRIP_INSTALLED_PRODUCT=$STRIP_INSTALLED_PRODUCT"
echo "JAVAC_DEFAULT_FLAGS=$JAVAC_DEFAULT_FLAGS"
echo "FILE_LIST=$FILE_LIST"
echo "JAVA_FRAMEWORK_RESOURCES_DIRS=$JAVA_FRAMEWORK_RESOURCES_DIRS"
echo "REMOVE_GIT_FROM_RESOURCES=$REMOVE_GIT_FROM_RESOURCES"
echo "CCHROOT=$CCHROOT"
echo "GCC_DYNAMIC_NO_PIC=$GCC_DYNAMIC_NO_PIC"
echo "PROJECT_FILE_PATH=$PROJECT_FILE_PATH"
echo "FRAMEWORK_SEARCH_PATHS=$FRAMEWORK_SEARCH_PATHS"
echo "EXECUTABLE_NAME=$EXECUTABLE_NAME"
echo "SUPPORTED_DEVICE_FAMILIES=$SUPPORTED_DEVICE_FAMILIES"
echo "EDITOR=$EDITOR"
echo "NO_COMMON=$NO_COMMON"
echo "PLATFORM_DEVELOPER_APPLICATIONS_DIR=$PLATFORM_DEVELOPER_APPLICATIONS_DIR"
echo "JAVA_COMPILER=$JAVA_COMPILER"
echo "HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=$HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS"
echo "VERSION_INFO_FILE=$VERSION_INFO_FILE"
echo "UNSTRIPPED_PRODUCT=$UNSTRIPPED_PRODUCT"
echo "LANG=$LANG"
echo "SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR=$SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR"
echo "JAVA_SOURCE_SUBDIR=$JAVA_SOURCE_SUBDIR"
echo "DEPLOYMENT_LOCATION=$DEPLOYMENT_LOCATION"
echo "SEPARATE_SYMBOL_EDIT=$SEPARATE_SYMBOL_EDIT"
echo "DEVELOPER_FRAMEWORKS_DIR=$DEVELOPER_FRAMEWORKS_DIR"
echo "SRCROOT=$SRCROOT"
echo "LOCAL_DEVELOPER_DIR=$LOCAL_DEVELOPER_DIR"
echo "REZ_OBJECTS_DIR=$REZ_OBJECTS_DIR"
echo "INFOPLIST_PATH=$INFOPLIST_PATH"
echo "CHOWN=$CHOWN"
echo "SYSTEM_DEVELOPER_JAVA_TOOLS_DIR=$SYSTEM_DEVELOPER_JAVA_TOOLS_DIR"
echo "PUBLIC_HEADERS_FOLDER_PATH=$PUBLIC_HEADERS_FOLDER_PATH"
echo "PROJECT_DIR=$PROJECT_DIR"
echo "JAVA_FOLDER_PATH=$JAVA_FOLDER_PATH"
echo "PASCAL_STRINGS=$PASCAL_STRINGS"
echo "COMPOSITE_SDK_DIRS=$COMPOSITE_SDK_DIRS"
echo "TEMP_FILE_DIR=$TEMP_FILE_DIR"
echo "PROJECT_TEMP_DIR=$PROJECT_TEMP_DIR"
echo "GCC_WARN_MISSING_PARENTHESES=$GCC_WARN_MISSING_PARENTHESES"
echo "MAC_OS_X_VERSION_MAJOR=$MAC_OS_X_VERSION_MAJOR"
echo "GCC_WARN_INITIALIZER_NOT_FULLY_BRACKETED=$GCC_WARN_INITIALIZER_NOT_FULLY_BRACKETED"
echo "i=$i"
echo "SYMROOT=$SYMROOT"
echo "GCC_WARN_CHECK_SWITCH_STATEMENTS=$GCC_WARN_CHECK_SWITCH_STATEMENTS"
echo "CP=$CP"
echo "SKIP_INSTALL=$SKIP_INSTALL"
echo "SCRIPT_INPUT_FILE_COUNT=$SCRIPT_INPUT_FILE_COUNT"
echo "JAVA_ARCHIVE_CLASSES=$JAVA_ARCHIVE_CLASSES"
echo "PLATFORM_DEVELOPER_TOOLS_DIR=$PLATFORM_DEVELOPER_TOOLS_DIR"
echo "DWARF_DSYM_FILE_NAME=$DWARF_DSYM_FILE_NAME"
echo "APPLE_INTERNAL_DOCUMENTATION_DIR=$APPLE_INTERNAL_DOCUMENTATION_DIR"
echo "SYSTEM_DEVELOPER_APPS_DIR=$SYSTEM_DEVELOPER_APPS_DIR"
echo "MAC_OS_X_VERSION_ACTUAL=$MAC_OS_X_VERSION_ACTUAL"
echo "LEX=$LEX"
echo "FRAMEWORK_FLAG_PREFIX=$FRAMEWORK_FLAG_PREFIX"
echo "INSTALL_ROOT=$INSTALL_ROOT"
echo "RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS=$RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS"
echo "HOME=$HOME"
echo "SHLVL=$SHLVL"
echo "COLORFGBG=$COLORFGBG"
echo "PLATFORM_DEVELOPER_LIBRARY_DIR=$PLATFORM_DEVELOPER_LIBRARY_DIR"
echo "EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=$EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS"
echo "PROFILING_CODE=$PROFILING_CODE"
echo "GENERATE_PROFILING_CODE=$GENERATE_PROFILING_CODE"
echo "SET_DIR_MODE_OWNER_GROUP=$SET_DIR_MODE_OWNER_GROUP"
echo "APPLY_RULES_IN_COPY_FILES=$APPLY_RULES_IN_COPY_FILES"
echo "GCC_WARN_UNUSED_VALUE=$GCC_WARN_UNUSED_VALUE"
echo "REMOVE_SVN_FROM_RESOURCES=$REMOVE_SVN_FROM_RESOURCES"
echo "RUN_CLANG_STATIC_ANALYZER=$RUN_CLANG_STATIC_ANALYZER"
echo "SYSTEM_LIBRARY_DIR=$SYSTEM_LIBRARY_DIR"
echo "DEVELOPER_BIN_DIR=$DEVELOPER_BIN_DIR"
echo "VERBOSE_PBXCP=$VERBOSE_PBXCP"
echo "XCODE_VERSION_MINOR=$XCODE_VERSION_MINOR"
echo "OBJC_ABI_VERSION=$OBJC_ABI_VERSION"
echo "FRAMEWORKS_FOLDER_PATH=$FRAMEWORKS_FOLDER_PATH"
echo "VALID_ARCHS=$VALID_ARCHS"
echo "INSTALL_PATH=$INSTALL_PATH"
echo "COMBINE_HIDPI_IMAGES=$COMBINE_HIDPI_IMAGES"
echo "CACHE_ROOT=$CACHE_ROOT"
echo "SYSTEM_DEVELOPER_DEMOS_DIR=$SYSTEM_DEVELOPER_DEMOS_DIR"
echo "PROJECT_DERIVED_FILE_DIR=$PROJECT_DERIVED_FILE_DIR"
echo "GCC_PREPROCESSOR_DEFINITIONS=$GCC_PREPROCESSOR_DEFINITIONS"
echo "JAVA_ARCHIVE_TYPE=$JAVA_ARCHIVE_TYPE"
echo "LEGACY_DEVELOPER_DIR=$LEGACY_DEVELOPER_DIR"
echo "SYSTEM_DEVELOPER_BIN_DIR=$SYSTEM_DEVELOPER_BIN_DIR"
echo "CODE_SIGN_IDENTITY=$CODE_SIGN_IDENTITY"
echo "DEBUGGING_SYMBOLS=$DEBUGGING_SYMBOLS"
echo "CODESIGNING_FOLDER_PATH=$CODESIGNING_FOLDER_PATH"
echo "LOGNAME=$LOGNAME"
echo "SHALLOW_BUNDLE=$SHALLOW_BUNDLE"
echo "PRECOMP_DESTINATION_DIR=$PRECOMP_DESTINATION_DIR"
echo "MACOSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET"
echo "PKGINFO_FILE_PATH=$PKGINFO_FILE_PATH"
echo "APPLE_INTERNAL_LIBRARY_DIR=$APPLE_INTERNAL_LIBRARY_DIR"
echo "BUILD_DIR=$BUILD_DIR"
echo "XCODE_VERSION_MAJOR=$XCODE_VERSION_MAJOR"
echo "PLATFORM_DEVELOPER_BIN_DIR=$PLATFORM_DEVELOPER_BIN_DIR"
echo "ARCHS_UNIVERSAL_IPHONE_OS=$ARCHS_UNIVERSAL_IPHONE_OS"
echo "GCC_WARN_UNUSED_VARIABLE=$GCC_WARN_UNUSED_VARIABLE"
echo "JIKES_DEFAULT_FLAGS=$JIKES_DEFAULT_FLAGS"
echo "INFOPLIST_FILE=$INFOPLIST_FILE"
echo "LINK_WITH_STANDARD_LIBRARIES=$LINK_WITH_STANDARD_LIBRARIES"
echo "LOCAL_LIBRARY_DIR=$LOCAL_LIBRARY_DIR"
echo "LC_CTYPE=$LC_CTYPE"
echo "CURRENT_VARIANT=$CURRENT_VARIANT"
echo "ALWAYS_SEARCH_USER_PATHS=$ALWAYS_SEARCH_USER_PATHS"
echo "USE_HEADER_SYMLINKS=$USE_HEADER_SYMLINKS"
echo "UID=$UID"
echo "ALTERNATE_GROUP=$ALTERNATE_GROUP"
echo "GCC_WARN_UNUSED_LABEL=$GCC_WARN_UNUSED_LABEL"
echo "SCRIPTS_FOLDER_PATH=$SCRIPTS_FOLDER_PATH"
echo "PLATFORM_DEVELOPER_SDK_DIR=$PLATFORM_DEVELOPER_SDK_DIR"
echo "KEEP_PRIVATE_EXTERNS=$KEEP_PRIVATE_EXTERNS"
echo "GCC_PRECOMPILE_PREFIX_HEADER=$GCC_PRECOMPILE_PREFIX_HEADER"
echo "SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR=$SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR"
echo "SUPPORTED_PLATFORMS=$SUPPORTED_PLATFORMS"
echo "SYSTEM_DEVELOPER_TOOLS_DOC_DIR=$SYSTEM_DEVELOPER_TOOLS_DOC_DIR"
echo "SYSTEM_DEVELOPER_USR_DIR=$SYSTEM_DEVELOPER_USR_DIR"
echo "IPHONEOS_DEPLOYMENT_TARGET=$IPHONEOS_DEPLOYMENT_TARGET"
echo "SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=$SCAN_ALL_SOURCE_FILES_FOR_INCLUDES"
echo "INFOSTRINGS_PATH=$INFOSTRINGS_PATH"
echo "GCC_PREFIX_HEADER=$GCC_PREFIX_HEADER"
echo "PLATFORM_PRODUCT_BUILD_VERSION=$PLATFORM_PRODUCT_BUILD_VERSION"
echo "GENERATE_MASTER_OBJECT_FILE=$GENERATE_MASTER_OBJECT_FILE"
echo "NATIVE_ARCH_ACTUAL=$NATIVE_ARCH_ACTUAL"
echo "DISPLAY=$DISPLAY"
echo "SYSTEM_CORE_SERVICES_DIR=$SYSTEM_CORE_SERVICES_DIR"
echo "ALTERNATE_OWNER=$ALTERNATE_OWNER"
echo "DEVELOPER_LIBRARY_DIR=$DEVELOPER_LIBRARY_DIR"
echo "INFOPLIST_EXPAND_BUILD_SETTINGS=$INFOPLIST_EXPAND_BUILD_SETTINGS"
echo "PREBINDING=$PREBINDING"
echo "SHARED_FRAMEWORKS_FOLDER_PATH=$SHARED_FRAMEWORKS_FOLDER_PATH"
echo "BUILD_STYLE=$BUILD_STYLE"
echo "LINK_FILE_LIST_normal_i386=$LINK_FILE_LIST_normal_i386"
echo "ARCHS=$ARCHS"
echo "ARCHS_STANDARD_32_BIT=$ARCHS_STANDARD_32_BIT"
echo "GENERATE_PKGINFO_FILE=$GENERATE_PKGINFO_FILE"
echo "CHMOD=$CHMOD"
echo "LINKER_DISPLAYS_MANGLED_NAMES=$LINKER_DISPLAYS_MANGLED_NAMES"
echo "DEBUG_INFORMATION_FORMAT=$DEBUG_INFORMATION_FORMAT"
echo "TARGET_TEMP_DIR=$TARGET_TEMP_DIR"
echo "NATIVE_ARCH=$NATIVE_ARCH"
echo "FRAMEWORK_VERSION=$FRAMEWORK_VERSION"
echo "WRAPPER_NAME=$WRAPPER_NAME"
echo "LC_TIME=$LC_TIME"
echo "HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=$HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT"
echo "TEMP_ROOT=$TEMP_ROOT"
echo "FIXED_FILES_DIR=$FIXED_FILES_DIR"
echo "SYSTEM_ADMIN_APPS_DIR=$SYSTEM_ADMIN_APPS_DIR"
echo "SOURCE_ROOT=$SOURCE_ROOT"
echo "USE_HEADERMAP=$USE_HEADERMAP"
echo "BUILD_ROOT=$BUILD_ROOT"
echo "EXECUTABLE_FOLDER_PATH=$EXECUTABLE_FOLDER_PATH"
echo "PRODUCT_SETTINGS_PATH=$PRODUCT_SETTINGS_PATH"

BUILD_PATH=${BUILD_DIR}
BUILD_PATH="/Users/DeViLsO/Desktop/iPhone/Builds"

RELEASE_DEVICE_DIR=${BUILD_PATH}/Release-iphoneos
RELEASE_SIMULATOR_DIR=${BUILD_PATH}/Release-iphonesimulator
STATICLIB=${BUILD_PATH}/_Library

if [ ! -e "$STATICLIB" ]; then
	mkdir "$STATICLIB"
fi

STATICLIB=${STATICLIB}/${Folder}

if [ ! -e "$STATICLIB" ]; then
	mkdir "$STATICLIB"
fi

lipo -output "${STATICLIB}/${FILE_NAME}" -create "${RELEASE_DEVICE_DIR}/${FILE_NAME}" "${RELEASE_SIMULATOR_DIR}/${FILE_NAME}"

rm "${RELEASE_DEVICE_DIR}/${FILE_NAME}"
rm "${RELEASE_SIMULATOR_DIR}/${FILE_NAME}"

#My Sources
YTHEADER_PATH=${STATICLIB}/YTHeader
if [ ! -e "$YTHEADER_PATH" ]; then
	mkdir "$YTHEADER_PATH"
fi
cp MySources/*.h "$YTHEADER_PATH"

#ASIHttpRequest
ASIHTTPREQUEST_PATH=${STATICLIB}/ASIHTTPRequest
if [ ! -e "$ASIHTTPREQUEST_PATH" ]; then
	mkdir "$ASIHTTPREQUEST_PATH"
fi
cp ASIHTTPRequest/*.h "$ASIHTTPREQUEST_PATH"

ASIHTTPREQUEST_ASIWEBPAGEREQUEST_PATH=${STATICLIB}/ASIHTTPRequest/ASIWebPageRequest
if [ ! -e "$ASIHTTPREQUEST_ASIWEBPAGEREQUEST_PATH" ]; then
	mkdir "$ASIHTTPREQUEST_ASIWEBPAGEREQUEST_PATH"
fi
cp ASIHTTPRequest/ASIWebPageRequest/*.h "$ASIHTTPREQUEST_ASIWEBPAGEREQUEST_PATH"

ASIHTTPREQUEST_S3_PATH=${STATICLIB}/ASIHTTPRequest/S3
if [ ! -e "$ASIHTTPREQUEST_S3_PATH" ]; then
	mkdir "$ASIHTTPREQUEST_S3_PATH"
fi
cp ASIHTTPRequest/S3/*.h "$ASIHTTPREQUEST_S3_PATH"

ASIHTTPREQUEST_CLOUDFILES_PATH=${STATICLIB}/ASIHTTPRequest/CloudFiles
if [ ! -e "$ASIHTTPREQUEST_CLOUDFILES_PATH" ]; then
	mkdir "$ASIHTTPREQUEST_CLOUDFILES_PATH"
fi
cp ASIHTTPRequest/CloudFiles/*.h "$ASIHTTPREQUEST_CLOUDFILES_PATH"

#AudioStreamer
AUDIOSTREAMER_PATH=${STATICLIB}/AudioStreamer
if [ ! -e "$AUDIOSTREAMER_PATH" ]; then
	mkdir "$AUDIOSTREAMER_PATH"
fi
cp AudioStreamer/*.h "$AUDIOSTREAMER_PATH"

#CocoaAMF
COCOAAMF_PATH=${STATICLIB}/CocoaAMF
if [ ! -e "$COCOAAMF_PATH" ]; then
	mkdir "$COCOAAMF_PATH"
fi
cp CocoaAMF/*.h "$COCOAAMF_PATH"

#CurledView
CURLEDVIEW_PATH=${STATICLIB}/CurledView
if [ ! -e "$CURLEDVIEW_PATH" ]; then
	mkdir "$CURLEDVIEW_PATH"
fi
cp CurledView/*.h "$CURLEDVIEW_PATH"

#DCRoundSwitch
DCROUNDSWITCH_PATH=${STATICLIB}/DCRoundSwitch
if [ ! -e "$DCROUNDSWITCH_PATH" ]; then
	mkdir "$DCROUNDSWITCH_PATH"
fi
cp DCRoundSwitch/*.h "$DCROUNDSWITCH_PATH"

#EGOPhotoViewer
EGOPHOTOVIEWER_PATH=${STATICLIB}/EGOPhotoViewer
if [ ! -e "$EGOPHOTOVIEWER_PATH" ]; then
	mkdir "$EGOPHOTOVIEWER_PATH"
fi
cp EGOPhotoViewer/*.h "$EGOPHOTOVIEWER_PATH"
cp -R EGOPhotoViewer/*.bundle "$EGOPHOTOVIEWER_PATH"

#FTUtils
FTUTILS_PATH=${STATICLIB}/FTUtils
if [ ! -e "$FTUTILS_PATH" ]; then
	mkdir "$FTUTILS_PATH"
fi
cp FTUtils/*.h "$FTUTILS_PATH"

#iCarousel
ICAROUSEL_PATH=${STATICLIB}/iCarousel
if [ ! -e "$ICAROUSEL_PATH" ]; then
	mkdir "$ICAROUSEL_PATH"
fi
cp iCarousel/*.h "$ICAROUSEL_PATH"

#PrettyKit
PRETTYKIT_PATH=${STATICLIB}/PrettyKit
if [ ! -e "$PRETTYKIT_PATH" ]; then
	mkdir "$PRETTYKIT_PATH"
fi
cp PrettyKit/*.h "$PRETTYKIT_PATH"

PRETTYKIT_CELLS_PATH=${PRETTYKIT_PATH}/cells
if [ ! -e "$PRETTYKIT_CELLS_PATH" ]; then
	mkdir "$PRETTYKIT_CELLS_PATH"
fi
cp PrettyKit/cells/*.h "$PRETTYKIT_CELLS_PATH"

#RTLabel
RTLABEL_PATH=${STATICLIB}/RTLabel
if [ ! -e "$RTLABEL_PATH" ]; then
	mkdir "$RTLABEL_PATH"
fi
cp RTLabel/*.h "$RTLABEL_PATH"

#SpriteAnimation
SPRITEANIMATION_PATH=${STATICLIB}/SpriteAnimation
if [ ! -e "$SPRITEANIMATION_PATH" ]; then
	mkdir "$SPRITEANIMATION_PATH"
fi
cp SpriteAnimation/*.h "$SPRITEANIMATION_PATH"

#SVProgressHUD
SVPROGRESSHUD_PATH=${STATICLIB}/SVProgressHUD
if [ ! -e "$SVPROGRESSHUD_PATH" ]; then
	mkdir "$SVPROGRESSHUD_PATH"
fi
cp SVProgressHUD/*.h "$SVPROGRESSHUD_PATH"
cp -R SVProgressHUD/*.bundle "$SVPROGRESSHUD_PATH"

#UAModalPanel
UAMODALPANEL_PATH=${STATICLIB}/UAModalPanel
if [ ! -e "$UAMODALPANEL_PATH" ]; then
	mkdir "$UAMODALPANEL_PATH"
fi
cp UAModalPanel/*.h "$UAMODALPANEL_PATH"
cp -R UAModalPanel/*.bundle "$UAMODALPANEL_PATH"

#ZipArchive
ZIP_PATH=${STATICLIB}/ZipArchive
if [ ! -e "$ZIP_PATH" ]; then
	mkdir "$ZIP_PATH"
fi
cp ZipArchive/*.h "$ZIP_PATH"

ZIP_MINI_PATH=${ZIP_PATH}/minizip
if [ ! -e "$ZIP_MINI_PATH" ]; then
	mkdir "$ZIP_MINI_PATH"
fi
cp ZipArchive/minizip/*.h "$ZIP_MINI_PATH"

find "${STATICLIB}" -name "_*" -exec rm -rf {} \;
find "${STATICLIB}" -name ".*" -exec rm -rf {} \;

open $STATICLIB

exit 0